version: "2"

services:
  zk:
    image: rdelvalle/zookeeper
    restart: on-failure
    ports:
    - "2181:2181"
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
    networks:
      aurora_cluster:
        ipv4_address: 192.168.33.2
    logging:
      driver: none 

  master:
    image: rdelvalle/mesos-master:1.5.1
    restart: on-failure
    ports:
    - "5050:5050"
    environment:
      MESOS_ZK: zk://192.168.33.2:2181/mesos
      MESOS_QUORUM: 1
      MESOS_HOSTNAME: localhost
      MESOS_CLUSTER: test-cluster
      MESOS_REGISTRY: replicated_log
      MESOS_WORK_DIR: /tmp/mesos
    networks:
      aurora_cluster:
        ipv4_address: 192.168.33.3
    depends_on:
    - zk
    logging:
      driver: none 

  agent-one:
    image: rdelvalle/mesos-agent:1.5.1
    pid: host
    restart: on-failure
    ports:
    - "5051:5051"
    environment:
      MESOS_MASTER: zk://192.168.33.2:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_HOSTNAME: agent1
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_SYSTEMD_ENABLE_SUPPORT: 'false'
      MESOS_WORK_DIR: /tmp/mesos
    networks:
      aurora_cluster:
        ipv4_address: 192.168.33.4

    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zk
    logging:
      driver: none 

  agent-two:
    image: rdelvalle/mesos-agent:1.5.1
    pid: host
    restart: on-failure
    ports:
    - "5061:5061"
    environment:
      MESOS_MASTER: zk://192.168.33.2:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_HOSTNAME: agent2
      MESOS_PORT: 5061
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_SYSTEMD_ENABLE_SUPPORT: 'false'
      MESOS_WORK_DIR: /tmp/mesos
    networks:
      aurora_cluster:
        ipv4_address: 192.168.33.5
    logging:
      driver: none 

    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zk

  aurora-one:
    image: lenhattan86/aurora:1.3
    pid: host
    ports:
    - "8081:8081"
    - "8080:8080"
    restart: on-failure
    environment:
      CLUSTER_NAME: test-cluster
      ZK_ENDPOINTS: "192.168.33.2:2181"
      MESOS_MASTER: "zk://192.168.33.2:2181/mesos"
      AURORA_HOME: /usr/share/aurora
      LOGDB_FILE_PATH: /var/db/aurorax
      MESOS_NATIVE_JAVA_LIBRARY: /usr/local/lib/libmesos.so
      ENABLE_MAGICMATCH: "true"
    networks:
      aurora_cluster:
        ipv4_address: 192.168.33.7
    volumes:
      - /Users/nhatle/projects/aurora/dist/install/aurora-scheduler:/usr/share/aurora
      - /Users/nhatle/projects/magicmatch:/usr/share/magicmatch

    depends_on:
    - zk
    - master
    - agent-one

      
networks:
  aurora_cluster:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.33.0/16
        gateway: 192.168.33.1